name: Nas_Ruas
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  postgres: ^2.6.1
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2

  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  fluttertoast: ^8.2.1

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.16
  camera: ^0.10.3+2

image_picker: ^0.8.7+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/logo-splash.png"
  



flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#fff"
  adaptive_icon_foreground: "assets/tela_inicial.jpg"

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets: 
    - assets/1024.jpg
    - assets/icon-android.png
    - assets/icon.png
    - assets/logo-splash.png
    - assets/tela_inicial.jpg
    - assets/profile-picture.png
    - assets/reset-password-icon.png
    - assets/logo-tela-login.png