name: sc_safely
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9

  
dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#fff"
  adaptive_icon_foreground: "assets/tela_inicial.png"

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
